plugins:
  - "@dotcom-tool-kit/component"
  - "@dotcom-tool-kit/mocha"
  - "@dotcom-tool-kit/eslint"
  - "@dotcom-tool-kit/prettier"
  - '@dotcom-tool-kit/husky-npm'
hooks:
  test:local:
    - Mocha
  test:ci:
    - Mocha
options:
  "@dotcom-tool-kit/mocha": {}
  "@dotcom-tool-kit/eslint": {}
  "@dotcom-tool-kit/prettier": {}
  "@dotcom-tool-kit/circleci": {}
